[package]
name = "m3vcf"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.15", features = ["serde"]}
bitvec = { version = "0.22", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"
