[package]
name = "app"
version = "0.1.0"
authors = ["Can Kockan <cankockan92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.0"
