[package]
name = "mmac"
version = "0.1.0"
authors = ["Hoon Cho <hcho06@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = {version = "0.13", features = ["rayon"]}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "impute"
harness = false

[[bin]]
name = "test_run"
path = "app/test_run.rs"
