[package]
name = "mmac"
version = "0.1.0"
authors = ["Hoon Cho <hcho06@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
